'use client'

import StyledComponentsRegistry from '@/styles/registry'

import * as S from './styles'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <S.Layout>
            <div className="b__header">
              <h1 className="bh__title">Agenda de Churras</h1>
            </div>
            <div className="b__page-container">{children}</div>
            <footer className="b__footer">
              <img
                // src={logo_trinca}
                alt="Trinca's logo"
                className="bf__image"
              />
            </footer>
          </S.Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
